# Utilise l'image Nginx de base
FROM nginx:alpine

# Supprime la configuration par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copie TA configuration personnalisée
COPY nginx.conf /etc/nginx/conf.d/

# Copie le reste de ton code frontend (HTML, JS, etc.)
# Si ton code est dans un sous-dossier 'public' ou 'dist', ajuste le chemin
COPY . /usr/share/nginx/html