# Chaque service est une brique de notre application MediaSchool.
services:
  # Le service frontend : utilise Nginx pour servir les fichiers statiques.
  frontend:
    build: ./frontend
    container_name: mediaschoold-frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Le site sera visible sur http://localhost:3000

  # Le service backend : la logique de l'application.
  backend:
    build: ./backend
    container_name: mediaschoold-backend
    restart: unless-stopped
    volumes:
      - ./backend/src:/var/www/html
    networks:
      - mediaschoold-net

  # Le service de base de données.
  db:
    image: mariadb:latest
    container_name: mediaschoold-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mediaschooldb
      MYSQL_USER: mediaschooluser
      MYSQL_PASSWORD: mediaschoolpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mediaschoold-net

  # L'interface pour gérer la base de données.
  phpmyadmin:
    image: phpmyadmin
    container_name: mediaschoold-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - mediaschoold-net
    depends_on:
      - db

# On définit le réseau pour que les services puissent communiquer.
networks:
  mediaschoold-net:

# On définit le volume pour que les données de la BDD ne soient pas perdues.
volumes:
  dbdata: