# On utilise une image officielle qui inclut PHP et le serveur web Apache,
# déjà préconfiguré pour fonctionner ensemble.
FROM php:8.2-apache

# On copie le code source de notre application (le dossier ./src)
# dans le dossier du serveur web à l'intérieur du conteneur (/var/www/html).
COPY ./src /var/www/html/